# MLOps Configuration File for Sign Language Recognition Model
run_id: 'default'
seed: 42

# --- Data Parameters (Must match preprocess.py) ---
sequence_length: 30
feature_dim: 126
num_classes: null # Will be updated by train_model.py based on labels.json

# --- Model Architecture ---
model_type: 'BiLSTM' # Options: BiLSTM, GRU
lstm_units: [128, 128]
dense_units: [256]
dropout_rate: 0.3
l2_reg: 0.001

# --- Training Hyperparameters ---
epochs: 80
batch_size: 32
learning_rate: 0.0001
optimizer: 'Adam'

# --- Callbacks / Stopping ---
early_stopping_patience: 15
reduce_lr_patience: 7
reduce_lr_factor: 0.5
min_lr: 1e-7

# --- Paths ---
data_dir: 'data/processed'
artifacts_dir: 'artifacts'
models_dir: 'models'
experiments_dir: 'experiments'
log_dir: 'logs'